version: '3.8'

services:
  # Server del Tris
  tris-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: tris-server
    hostname: tris-server
    ports:
      - "${EXTERNAL_PORT:-8080}:${PORT:-8080}"
    environment:
      - PORT=${PORT:-8080}
      - MAX_CLIENTS=${MAX_CLIENTS:-100}
      - DEBUG=${DEBUG:-1}
    networks:
      - tris-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "netstat -ln | grep :8080 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Client del Tris (template per scaling)
  tris-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      tris-server:
        condition: service_healthy
    environment:
      - SERVER_HOST=tris-server
      - SERVER_PORT=${PORT:-8080}
      - CLIENT_NAME=${CLIENT_NAME:-Player}
    networks:
      - tris-network
    stdin_open: true    # Necessario per l'input interattivo
    tty: true          # Necessario per l'output colorato
    profiles: ["client"]  # Non avviato di default

networks:
  tris-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16